### PR TITLE
Adding Oric system

### PR DESCRIPTION
**Pull request by dma-coco**
SystemDefs modified, and Oric system files added

### CODE REVIEW

**Comment by dma-coco** [comment]
Proposition to add 6502 system Oric Atmos.

**Comment by dma-coco** [comment]
Proposition to add. I'm not familiar with Git functions and have closed last request

**Comment by fadden** [comment]
Attempting to create a new project with the symbol files generates the following:

File RT:Oric/ATMOS-ROM.sym65:
  Line 181: warning: Syntax error
  Line 253: warning: Syntax error
  Line 306: warning: Syntax error
  Line 307: warning: Syntax error

Line 181 starts with a ':' rather than ';'.  Line 253 has a symbol with a space in it.  Line 306/307 use '!' and '&' as symbols, which is not allowed (must be [A-Za-z0-9_] and start with letter or underscore).

**Comment by dma-coco** [comment]
Thanks for feedback. Files have been modified

**Comment by fadden** [comment]
Looks good; changes merged. Let me know if you want me to post a development release on the releases page.

**Comment by dma-coco** [comment]
Thanks Andy. It could be a good idea to release it with the Oric add as i
intend to communicate in the oric community about your soft.
Sorry for the 1st errors in my file. I've tested it with an oric prg and it
seems to work fine

Didier

Le sam. 3 juil. 2021 à 23:49, Andy McFadden ***@***.***> a
écrit :

**Comment by fadden** [comment]
I've uploaded v1.7.5-dev1 to https://github.com/fadden/6502bench/releases .

I marked it as a development "pre-release", which means the contents aren't guaranteed to be stable.  So if you want to change the files around in ways that break things, it's allowed.  (I mean, it's always "allowed", but now you can do it and you don't have to feel bad afterward.)

**Comment by dma-coco** [comment]
Thanks a lot.
I've produce our mag (ceo-mag : ceo.oric.org soon) and i'm very happy for
our community ; and apple ii one as l'll attempt soon at kansasfest online
;)
Didier

Le dim. 4 juil. 2021 à 18:48, Andy McFadden ***@***.***> a
écrit :

**Pull request merged**
